# Generated by Tofuinit

variable "region" {
  type = string
}

variable "subnet_ids" {
  type = list(string)
}
variable "vpc_id" {
  type = string
}

variable "instance_type" {
  type    = string
  default = "t3.micro"
}

variable "ami_name" {
  type    = string
  default = "al2023-ami-2023.*-x86_64"
}

variable "owners" {
  type    = string
  default = "amazon"
}

variable "ec2_name" {
  type    = string
  default = "demo"
}

variable "cidr_block_vpc" {
  type = string
}

variable "cidr_block_vpc_tgw" {
  type = string
}

variable "tgw_enabled" {
  type = bool
  default = false
}

variable "policy_arns" {
  description = "List of policy ARNs to attach to the role"
  type        = list(string)
}